<?php

/*!
 * ifsoft.co.uk
 *
 * http://ifsoft.com.ua, https://ifsoft.co.uk, https://raccoonsquare.com
 * raccoonsquare@gmail.com
 *
 * Copyright 2012-2020 Demyanchuk Dmitry (raccoonsquare@gmail.com)
 */
    
if (!defined("APP_SIGNATURE")) {

    header("Location: /");
    exit;
}

$C['APP_TYPE_ALL'] = -1;
$C['APP_TYPE_UNKNOWN'] = 0;
$C['APP_TYPE_WEB'] = 1;
$C['APP_TYPE_ANDROID'] = 2;
$C['APP_TYPE_IOS'] = 3;

$C['ERROR_SUCCESS'] = 0;

$C['ERROR_UNKNOWN'] = 100;
$C['ERROR_ACCESS_TOKEN'] = 101;

$C['ERROR_LOGIN_TAKEN'] = 300;
$C['ERROR_EMAIL_TAKEN'] = 301;
$C['ERROR_FACEBOOK_ID_TAKEN'] = 302;
$C['ERROR_PHONE_TAKEN'] = 303;

$C['ERROR_ACCOUNT_ID'] = 400;

$C['ERROR_FILE_SIZE_BIG'] = 501;
$C['ERROR_FILE_SIZE_SMALL'] = 502;

$C['ERROR_IMAGE_FILE_FORMAT'] = 503;
$C['ERROR_IMAGE_FILE_WIDTH_HEIGHT'] = 504;

$C['ERROR_CLIENT_ID'] = 19100;
$C['ERROR_CLIENT_SECRET'] = 19101;

$C['DISABLE_LIKES_GCM'] = 0;
$C['ENABLE_LIKES_GCM'] = 1;

$C['DISABLE_COMMENTS_GCM'] = 0;
$C['ENABLE_COMMENTS_GCM'] = 1;

$C['DISABLE_FOLLOWERS_GCM'] = 0;
$C['ENABLE_FOLLOWERS_GCM'] = 1;

$C['DISABLE_MESSAGES_GCM'] = 0;
$C['ENABLE_MESSAGES_GCM'] = 1;

$C['DISABLE_GIFTS_GCM'] = 0;
$C['ENABLE_GIFTS_GCM'] = 1;

$C['SEX_UNKNOWN'] = 0;
$C['SEX_MALE'] = 1;
$C['SEX_FEMALE'] = 2;

$C['USER_CREATED_SUCCESSFULLY'] = 0;
$C['USER_CREATE_FAILED'] = 1;
$C['USER_ALREADY_EXISTED'] = 2;
$C['USER_BLOCKED'] = 3;
$C['USER_NOT_FOUND'] = 4;
$C['USER_LOGIN_SUCCESSFULLY'] = 5;
$C['EMPTY_DATA'] = 6;
$C['ERROR_API_KEY'] = 7;

$C['NOTIFY_TYPE_LIKE'] = 0;
$C['NOTIFY_TYPE_FOLLOWER'] = 1;
$C['NOTIFY_TYPE_MESSAGE'] = 2;
$C['NOTIFY_TYPE_COMMENT'] = 3;
$C['NOTIFY_TYPE_COMMENT_REPLY'] = 4;
$C['NOTIFY_TYPE_FRIEND_REQUEST_ACCEPTED'] = 5;
$C['NOTIFY_TYPE_GIFT'] = 6;
//$C['NOTIFY_TYPE_REVIEW'] = 7;

$C['NOTIFY_TYPE_REVIEW'] = 14;
$C['NOTIFY_TYPE_FRIEND_REQUEST'] = 15;
$C['NOTIFY_TYPE_REPOST'] = 16;
$C['NOTIFY_TYPE_POST'] = 17;
$C['NOTIFY_TYPE_MENTION'] = 18;

$C['NOTIFY_TYPE_ITEM_APPROVED'] = 19;
$C['NOTIFY_TYPE_ITEM_REJECTED'] = 20;

$C['GCM_NOTIFY_PROFILE_PHOTO_APPROVE'] = 1003;
$C['GCM_NOTIFY_PROFILE_PHOTO_REJECT'] = 1004;
$C['GCM_NOTIFY_PROFILE_COVER_APPROVE'] = 1007;
$C['GCM_NOTIFY_PROFILE_COVER_REJECT'] = 1008;

$C['NOTIFY_TYPE_PROFILE_PHOTO_APPROVE'] = 2003;
$C['NOTIFY_TYPE_PROFILE_PHOTO_REJECT'] = 2004;
$C['NOTIFY_TYPE_PROFILE_COVER_APPROVE'] = 2007;
$C['NOTIFY_TYPE_PROFILE_COVER_REJECT'] = 2008;

$C['GCM_NOTIFY_CONFIG'] = 0;
$C['GCM_NOTIFY_SYSTEM'] = 1;
$C['GCM_NOTIFY_CUSTOM'] = 2;
$C['GCM_NOTIFY_LIKE'] = 3;
$C['GCM_NOTIFY_ANSWER'] = 4;
$C['GCM_NOTIFY_QUESTION'] = 5;
$C['GCM_NOTIFY_COMMENT'] = 6;
$C['GCM_NOTIFY_FOLLOWER'] = 7;
$C['GCM_NOTIFY_PERSONAL'] = 8;
$C['GCM_NOTIFY_MESSAGE'] = 9;
$C['GCM_NOTIFY_COMMENT_REPLY'] = 10;
$C['GCM_NOTIFY_GIFT'] = 14;
$C['GCM_NOTIFY_REVIEW'] = 15;

$C['GCM_NOTIFY_ITEM_APPROVED'] = 100;
$C['GCM_NOTIFY_ITEM_REJECTED'] = 101;

$C['ACCOUNT_STATE_ENABLED'] = 0;
$C['ACCOUNT_STATE_DISABLED'] = 1;
$C['ACCOUNT_STATE_BLOCKED'] = 2;
$C['ACCOUNT_STATE_DEACTIVATED'] = 3;

$C['ACCOUNT_TYPE_USER'] = 0;
$C['ACCOUNT_TYPE_GROUP'] = 1;
$C['ACCOUNT_TYPE_PAGE'] = 2;

$C['ACCOUNT_ACCESS_LEVEL_AVAILABLE_TO_ALL'] = 0;
$C['ACCOUNT_ACCESS_LEVEL_AVAILABLE_TO_FRIENDS'] = 1;

$C['ADMIN_ACCESS_LEVEL_NULL'] = -1;
$C['ADMIN_ACCESS_LEVEL_FULL'] = 0;
$C['ADMIN_ACCESS_LEVEL_MODERATOR'] = 1;
$C['ADMIN_ACCESS_LEVEL_GUEST'] = 2;

$C['ITEM_RATING_LIKE_VALUE'] = 5;
$C['ITEM_RATING_SHARE_VALUE'] = 4;
$C['ITEM_RATING_COMMENT_VALUE'] = 3;
$C['ITEM_RATING_REPOST_VALUE'] = 3;
$C['ITEM_RATING_VIEW_VALUE'] = 1;
$C['ITEM_RATING_PHONE_VIEW_VALUE'] = 2;

$C['ITEM_TYPE_ALL'] = -1;
$C['ITEM_TYPE_DEFAULT'] = 0;
$C['ITEM_TYPE_MEDIA'] = 1;
$C['ITEM_TYPE_CLASSIFIED'] = 2;

$C['REPORT_TYPE_ITEM'] = 0;
$C['REPORT_TYPE_PROFILE'] = 1;
$C['REPORT_TYPE_MESSAGE'] = 2;
$C['REPORT_TYPE_COMMENT'] = 3;

$C['FINDER_UNSET'] = 0;
$C['FINDER_TRUE'] = 1;
$C['FINDER_FALSE'] = 2;

$C['FILTER_ALL'] = 0;
$C['FILTER_HIDE'] = 1;
$C['FILTER_ONLY_YES'] = 2;
$C['FILTER_ONLY_NO'] = 3;

$C['ACTIONS_FAIL_SIGNIN'] = 0;
$C['ACTIONS_FAIL_SIGNUP'] = 1;
$C['ACTIONS_ITEM_SEARCH'] = 2;

$C['DEFAULT_PHOTO_IMG'] = "/img/profile_default_photo.png";
$C['DEFAULT_COVER_IMG'] = "/img/profile_default_cover.png";